// Port of netbird client/internal/dns/file_unix.go and file_parser_unix.go
// (v0.79.0), BSD-3-Clause. The resolvconf(8) backend (resolvconf_unix.go) is
// M14+ and not ported; the repair watcher (file_repair_unix.go) is not ported.

const std = @import("std");
const linux = std.os.linux;
const builtin = @import("builtin");

const header_first_line = "# Generated by NetBird";
pub const default_resolv_conf_path = "/etc/resolv.conf";
pub const backup_suffix = ".original.netbird";
pub const max_line_chars_limit = 256;
pub const max_search_domains = 6;

fn failed(rc: usize) bool {
    return rc > 0xfffffffffffff000;
}

pub const Error = error{
    OpenFailed,
    ReadFailed,
    WriteFailed,
    StatFailed,
    UnlinkFailed,
    EmptyFile,
    OutOfMemory,
};

/// Parsed resolv.conf (Go resolvConf). Addresses stay as validated text.
pub const ResolvConf = struct {
    name_servers: []const []const u8 = &.{},
    search_domains: []const []const u8 = &.{},
    others: []const []const u8 = &.{},
};

fn isValidAddr(text: []const u8) bool {
    if (text.len == 0 or text.len > 45) return false;
    var buf: [46]u8 = undefined;
    @memcpy(buf[0..text.len], text);
    _ = std.Io.net.IpAddress.parse(buf[0..text.len], 0) catch return false;
    return true;
}

/// Port of parseResolvConfFile: comments, "domain" and "options ... rotate"
/// lines are dropped, "search" REPLACES the list, valid "nameserver" lines
/// accumulate, everything else lands in others. An empty file is an error.
pub fn parse(alloc: std.mem.Allocator, contents: []const u8) Error!ResolvConf {
    if (contents.len == 0) return Error.EmptyFile;

    var name_servers: std.ArrayListUnmanaged([]const u8) = .empty;
    var search_domains: std.ArrayListUnmanaged([]const u8) = .empty;
    var others: std.ArrayListUnmanaged([]const u8) = .empty;

    var lines = std.mem.splitScalar(u8, contents, '\n');
    while (lines.next()) |raw_line| {
        const line = std.mem.trim(u8, raw_line, " \t\r");
        if (std.mem.startsWith(u8, line, "#")) continue;
        if (std.mem.startsWith(u8, line, "domain")) continue;

        if (std.mem.startsWith(u8, line, "options") and std.mem.indexOf(u8, line, "rotate") != null) {
            // drop the rotate option; a line with nothing else is skipped
            var rebuilt: std.ArrayListUnmanaged(u8) = .empty;
            var fields = std.mem.tokenizeAny(u8, line, " \t");
            var count: usize = 0;
            while (fields.next()) |f| {
                if (std.mem.eql(u8, f, "rotate")) continue;
                if (count > 0) try rebuilt.append(alloc, ' ');
                try rebuilt.appendSlice(alloc, f);
                count += 1;
            }
            if (count <= 1) continue;
            try others.append(alloc, rebuilt.items);
            continue;
        }

        if (std.mem.startsWith(u8, line, "search")) {
            var fields: std.ArrayListUnmanaged([]const u8) = .empty;
            var it = std.mem.tokenizeAny(u8, line, " \t");
            while (it.next()) |f| try fields.append(alloc, f);
            if (fields.items.len < 2) continue;
            search_domains = .empty;
            try search_domains.appendSlice(alloc, fields.items[1..]);
            continue;
        }

        if (std.mem.startsWith(u8, line, "nameserver")) {
            var fields: [3][]const u8 = undefined;
            var n: usize = 0;
            var it = std.mem.tokenizeAny(u8, line, " \t");
            while (it.next()) |f| {
                if (n < 3) fields[n] = f;
                n += 1;
            }
            if (n != 2) continue;
            if (isValidAddr(fields[1])) {
                try name_servers.append(alloc, try alloc.dupe(u8, fields[1]));
            }
            continue;
        }

        if (line.len != 0) {
            try others.append(alloc, try alloc.dupe(u8, line));
        }
    }

    return .{
        .name_servers = name_servers.items,
        .search_domains = search_domains.items,
        .others = others.items,
    };
}

/// Port of prepareResolvConfContent with the backup path made explicit (the
/// second header line points at it). The search line must already be merged
/// and capped by mergeSearchDomains.
pub fn prepareContent(
    alloc: std.mem.Allocator,
    backup_path: []const u8,
    search_domains: []const []const u8,
    name_servers: []const []const u8,
    others: []const []const u8,
) Error![]u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    try buf.appendSlice(alloc, header_first_line);
    try buf.appendSlice(alloc, "\n# The original file can be restored from ");
    try buf.appendSlice(alloc, backup_path);
    try buf.appendSlice(alloc, "\n\n");

    for (others) |cfg_line| {
        try buf.appendSlice(alloc, cfg_line);
        try buf.append(alloc, '\n');
    }

    if (search_domains.len > 0) {
        try buf.appendSlice(alloc, "search");
        for (search_domains) |sd| {
            try buf.append(alloc, ' ');
            try buf.appendSlice(alloc, sd);
        }
        try buf.append(alloc, '\n');
    }

    for (name_servers) |ns| {
        try buf.appendSlice(alloc, "nameserver ");
        try buf.appendSlice(alloc, ns);
        try buf.append(alloc, '\n');
    }

    return buf.items;
}

/// Port of mergeSearchDomains + validateAndFillSearchDomains: NetBird domains
/// first, then the original ones, deduplicated, the "search" line capped at
/// max_line_chars_limit characters and max_search_domains entries.
pub fn mergeSearchDomains(
    alloc: std.mem.Allocator,
    nb_domains: []const []const u8,
    original_domains: []const []const u8,
) Error![]const []const u8 {
    var list: std.ArrayListUnmanaged([]const u8) = .empty;
    var line_chars: usize = "search".len;

    for ([_][]const []const u8{ nb_domains, original_domains }) |vs| {
        for (vs) |sd| {
            var duplicated = false;
            for (list.items) |fs| {
                if (std.mem.eql(u8, fs, sd)) {
                    duplicated = true;
                    break;
                }
            }
            if (duplicated) continue;

            const tmp_chars = line_chars + 1 + sd.len;
            if (tmp_chars > max_line_chars_limit) continue;
            line_chars = tmp_chars;

            if (list.items.len >= max_search_domains) continue;
            try list.append(alloc, sd);
        }
    }
    return list.items;
}

pub fn fileExists(path: [*:0]const u8) bool {
    return linux.access(path, 0) == 0;
}

/// Read a whole file (lseek for the size; no fstat on aarch64 4.9).
pub fn readFileAlloc(alloc: std.mem.Allocator, path: [*:0]const u8) Error![]u8 {    const fd_usize = linux.open(path, .{ .ACCMODE = .RDONLY, .CLOEXEC = true }, 0);
    if (failed(fd_usize)) return Error.OpenFailed;
    const fd: linux.fd_t = @intCast(fd_usize);
    defer _ = linux.close(fd);
    // no fstat on aarch64 4.9: size via lseek (see AGENTS.md)
    const size = linux.lseek(fd, 0, linux.SEEK.END);
    if (failed(size)) return Error.StatFailed;
    _ = linux.lseek(fd, 0, linux.SEEK.SET); // rewind after sizing
    const buf = try alloc.alloc(u8, @intCast(size));
    var got: usize = 0;
    while (got < buf.len) {
        const n = linux.read(fd, buf[got..].ptr, buf.len - got);
        if (failed(n) or n == 0) return Error.ReadFailed;
        got += n;
    }
    return buf;
}

/// Legacy newfstatat/fstatat exists on Linux 4.9, unlike statx.
/// Kernel stat is 144 bytes on x86_64 and 128 bytes on aarch64.
pub fn fileMode(path: [*:0]const u8) Error!u32 {
    var stat: [144]u8 align(8) = undefined;
    const rc = linux.syscall4(.newfstatat,
        @bitCast(@as(isize, linux.AT.FDCWD)), @intFromPtr(path), @intFromPtr(&stat), 0);
    if (failed(rc)) return Error.StatFailed;
    const offset = if (builtin.cpu.arch == .aarch64) 16 else 24;
    return std.mem.readInt(u32, stat[offset..][0..4], .little) & 0o7777;
}

fn writeFile(path: [*:0]const u8, data: []const u8, mode: u32) Error!void {
    const fd_usize = linux.open(path, .{ .ACCMODE = .WRONLY, .CREAT = true, .TRUNC = true }, mode);
    if (failed(fd_usize)) return Error.WriteFailed;
    const fd: linux.fd_t = @intCast(fd_usize);
    defer _ = linux.close(fd);
    var sent: usize = 0;
    while (sent < data.len) {
        const n = linux.write(fd, data[sent..].ptr, data.len - sent);
        if (failed(n)) return Error.WriteFailed;
        sent += n;
    }
}

/// Port of copyFile: creation uses the source mode, existing modes stay unchanged
/// as with os.WriteFile upstream.
fn copyFile(src: [*:0]const u8, dest: [*:0]const u8) Error!void {
    const data = try readFileAlloc(std.heap.page_allocator, src);
    defer std.heap.page_allocator.free(data);
    try writeFile(dest, data, try fileMode(src));
}

/// Port of fileConfigurator with the paths made parameters so tests can work
/// on a temp directory instead of the host /etc/resolv.conf.
pub const FileConfigurator = struct {
    alloc: std.mem.Allocator,
    config_path: [:0]const u8,
    backup_path: [:0]const u8,
    original_nameservers: []const []const u8 = &.{},
    original_perms: u32 = 0,

    pub fn backupExists(f: *const FileConfigurator) bool {
        return fileExists(f.backup_path.ptr);
    }

    /// Port of fileConfigurator.backup.
    pub fn backup(f: *FileConfigurator) Error!void {
        f.original_perms = try fileMode(f.config_path.ptr);
        try copyFile(f.config_path.ptr, f.backup_path.ptr);
    }

    /// Port of fileConfigurator.restore: copy the backup over the config and
    /// remove the backup.
    pub fn restore(f: *FileConfigurator) Error!void {
        try copyFile(f.backup_path.ptr, f.config_path.ptr);
        if (failed(linux.unlink(f.backup_path.ptr))) return Error.UnlinkFailed;
    }

    /// Port of applyDNSConfig/updateConfig: the caller must have backed the
    /// config up first (Go checks isBackupFileExist before calling backup);
    /// the original file is parsed from the backup, search domains merged and
    /// the managed content written. A write error restores the original.
    /// `nb_search_domains` are the NetBird domains (HostDNSConfig already
    /// filtered); `server_ip` is the single nameserver written.
    pub fn apply(
        f: *FileConfigurator,
        nb_search_domains: []const []const u8,
        server_ip: []const u8,
    ) Error!void {
        const raw = try readFileAlloc(f.alloc, f.backup_path.ptr);
        defer f.alloc.free(raw);
        // parse failure behaves like Go's: log-and-continue with empty state
        const orig = parse(f.alloc, raw) catch ResolvConf{};

        // keep the original nameservers past this call (Go keeps the parsed
        // struct); the search domains and others are only used below
        var duped_ns: std.ArrayListUnmanaged([]const u8) = .empty;
        for (orig.name_servers) |ns| try duped_ns.append(f.alloc, try f.alloc.dupe(u8, ns));
        f.original_nameservers = duped_ns.items;

        const merged = try mergeSearchDomains(f.alloc, nb_search_domains, orig.search_domains);
        const name_servers = [1][]const u8{server_ip};
        const content = try prepareContent(f.alloc, f.backup_path, merged, &name_servers, orig.others);

        writeFile(f.config_path.ptr, content, f.original_perms) catch |err| {
            f.restore() catch {}; // Go logs the restore failure and returns the write error
            return err;
        };
    }

    /// Port of restoreHostDNS (without the repair watcher, M14+).
    pub fn restoreHostDNS(f: *FileConfigurator) Error!void {
        return f.restore();
    }
};
