// Port of netbird client/internal/dns/file_unix.go and file_parser_unix.go
// (v0.79.0), BSD-3-Clause. The resolvconf(8) backend (resolvconf_unix.go) is
// M14+ and not ported; the repair watcher (file_repair_unix.go) is not ported.

const std = @import("std");
const linux = std.os.linux;
const builtin = @import("builtin");

const header_first_line = "# Generated by NetBird";
pub const default_resolv_conf_path = "/etc/resolv.conf";
pub const backup_suffix = ".original.netbird";
pub const max_line_chars_limit = 256;
pub const max_search_domains = 6;

fn failed(rc: usize) bool {
    return rc > 0xfffffffffffff000;
}

pub const Error = error{
    OpenFailed,
    ReadFailed,
    WriteFailed,
    StatFailed,
    UnlinkFailed,
    EmptyFile,
    InvalidState,
    OutOfMemory,
};

/// Parsed resolv.conf (Go resolvConf). Addresses stay as validated text.
pub const ResolvConf = struct {
    name_servers: []const []const u8 = &.{},
    search_domains: []const []const u8 = &.{},
    others: []const []const u8 = &.{},
};

fn isValidAddr(text: []const u8) bool {
    if (text.len == 0 or text.len > 45) return false;
    var buf: [46]u8 = undefined;
    @memcpy(buf[0..text.len], text);
    _ = std.Io.net.IpAddress.parse(buf[0..text.len], 0) catch return false;
    return true;
}

/// Port of parseResolvConfFile: comments, "domain" and "options ... rotate"
/// lines are dropped, "search" REPLACES the list, valid "nameserver" lines
/// accumulate, everything else lands in others. An empty file is an error.
pub fn parse(alloc: std.mem.Allocator, contents: []const u8) Error!ResolvConf {
    if (contents.len == 0) return Error.EmptyFile;

    var name_servers: std.ArrayListUnmanaged([]const u8) = .empty;
    var search_domains: std.ArrayListUnmanaged([]const u8) = .empty;
    var others: std.ArrayListUnmanaged([]const u8) = .empty;

    var lines = std.mem.splitScalar(u8, contents, '\n');
    while (lines.next()) |raw_line| {
        const line = std.mem.trim(u8, raw_line, " \t\r");
        if (std.mem.startsWith(u8, line, "#")) continue;
        if (std.mem.startsWith(u8, line, "domain")) continue;

        if (std.mem.startsWith(u8, line, "options") and std.mem.indexOf(u8, line, "rotate") != null) {
            // drop the rotate option; a line with nothing else is skipped
            var rebuilt: std.ArrayListUnmanaged(u8) = .empty;
            var fields = std.mem.tokenizeAny(u8, line, " \t");
            var count: usize = 0;
            while (fields.next()) |f| {
                if (std.mem.eql(u8, f, "rotate")) continue;
                if (count > 0) try rebuilt.append(alloc, ' ');
                try rebuilt.appendSlice(alloc, f);
                count += 1;
            }
            if (count <= 1) continue;
            try others.append(alloc, rebuilt.items);
            continue;
        }

        if (std.mem.startsWith(u8, line, "search")) {
            var fields: std.ArrayListUnmanaged([]const u8) = .empty;
            var it = std.mem.tokenizeAny(u8, line, " \t");
            while (it.next()) |f| try fields.append(alloc, f);
            if (fields.items.len < 2) continue;
            search_domains = .empty;
            try search_domains.appendSlice(alloc, fields.items[1..]);
            continue;
        }

        if (std.mem.startsWith(u8, line, "nameserver")) {
            var fields: [3][]const u8 = undefined;
            var n: usize = 0;
            var it = std.mem.tokenizeAny(u8, line, " \t");
            while (it.next()) |f| {
                if (n < 3) fields[n] = f;
                n += 1;
            }
            if (n != 2) continue;
            if (isValidAddr(fields[1])) {
                try name_servers.append(alloc, try alloc.dupe(u8, fields[1]));
            }
            continue;
        }

        if (line.len != 0) {
            try others.append(alloc, try alloc.dupe(u8, line));
        }
    }

    return .{
        .name_servers = name_servers.items,
        .search_domains = search_domains.items,
        .others = others.items,
    };
}

/// Port of prepareResolvConfContent with the backup path made explicit (the
/// second header line points at it). The search line must already be merged
/// and capped by mergeSearchDomains.
pub fn prepareContent(
    alloc: std.mem.Allocator,
    backup_path: []const u8,
    search_domains: []const []const u8,
    name_servers: []const []const u8,
    others: []const []const u8,
) Error![]u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    try buf.appendSlice(alloc, header_first_line);
    try buf.appendSlice(alloc, "\n# The original file can be restored from ");
    try buf.appendSlice(alloc, backup_path);
    try buf.appendSlice(alloc, "\n\n");

    for (others) |cfg_line| {
        try buf.appendSlice(alloc, cfg_line);
        try buf.append(alloc, '\n');
    }

    if (search_domains.len > 0) {
        try buf.appendSlice(alloc, "search");
        for (search_domains) |sd| {
            try buf.append(alloc, ' ');
            try buf.appendSlice(alloc, sd);
        }
        try buf.append(alloc, '\n');
    }

    for (name_servers) |ns| {
        try buf.appendSlice(alloc, "nameserver ");
        try buf.appendSlice(alloc, ns);
        try buf.append(alloc, '\n');
    }

    return buf.items;
}

/// Port of mergeSearchDomains + validateAndFillSearchDomains: NetBird domains
/// first, then the original ones, deduplicated, the "search" line capped at
/// max_line_chars_limit characters and max_search_domains entries.
pub fn mergeSearchDomains(
    alloc: std.mem.Allocator,
    nb_domains: []const []const u8,
    original_domains: []const []const u8,
) Error![]const []const u8 {
    var list: std.ArrayListUnmanaged([]const u8) = .empty;
    var line_chars: usize = "search".len;

    for ([_][]const []const u8{ nb_domains, original_domains }) |vs| {
        for (vs) |sd| {
            var duplicated = false;
            for (list.items) |fs| {
                if (std.mem.eql(u8, fs, sd)) {
                    duplicated = true;
                    break;
                }
            }
            if (duplicated) continue;

            const tmp_chars = line_chars + 1 + sd.len;
            if (tmp_chars > max_line_chars_limit) continue;
            line_chars = tmp_chars;

            if (list.items.len >= max_search_domains) continue;
            try list.append(alloc, sd);
        }
    }
    return list.items;
}

pub fn fileExists(path: [*:0]const u8) bool {
    return linux.access(path, 0) == 0;
}

/// Read a whole file (lseek for the size; no fstat on aarch64 4.9).
pub fn readFileAlloc(alloc: std.mem.Allocator, path: [*:0]const u8) Error![]u8 {
    const fd_usize = linux.open(path, .{ .ACCMODE = .RDONLY, .CLOEXEC = true }, 0);
    if (failed(fd_usize)) return Error.OpenFailed;
    const fd: linux.fd_t = @intCast(fd_usize);
    defer _ = linux.close(fd);
    // no fstat on aarch64 4.9: size via lseek (see AGENTS.md)
    const size = linux.lseek(fd, 0, linux.SEEK.END);
    if (failed(size)) return Error.StatFailed;
    _ = linux.lseek(fd, 0, linux.SEEK.SET); // rewind after sizing
    const buf = try alloc.alloc(u8, @intCast(size));
    errdefer alloc.free(buf);
    var got: usize = 0;
    while (got < buf.len) {
        const n = linux.read(fd, buf[got..].ptr, buf.len - got);
        if (failed(n) or n == 0) return Error.ReadFailed;
        got += n;
    }
    return buf;
}

/// Legacy newfstatat/fstatat exists on Linux 4.9, unlike statx.
/// Kernel stat is 144 bytes on x86_64 and 128 bytes on aarch64.
pub fn fileMode(path: [*:0]const u8) Error!u32 {
    var stat: [144]u8 align(8) = undefined;
    const rc = linux.syscall4(.newfstatat, @bitCast(@as(isize, linux.AT.FDCWD)), @intFromPtr(path), @intFromPtr(&stat), 0);
    if (failed(rc)) return Error.StatFailed;
    const offset = if (builtin.cpu.arch == .aarch64) 16 else 24;
    return std.mem.readInt(u32, stat[offset..][0..4], .little) & 0o7777;
}

fn writeFile(path: [*:0]const u8, data: []const u8, mode: u32) Error!void {
    const fd_usize = linux.open(path, .{ .ACCMODE = .WRONLY, .CREAT = true, .TRUNC = true }, mode);
    if (failed(fd_usize)) return Error.WriteFailed;
    const fd: linux.fd_t = @intCast(fd_usize);
    defer _ = linux.close(fd);
    var sent: usize = 0;
    while (sent < data.len) {
        const n = linux.write(fd, data[sent..].ptr, data.len - sent);
        if (failed(n)) return Error.WriteFailed;
        sent += n;
    }
}

/// Port of copyFile: creation uses the source mode, existing modes stay unchanged
/// as with os.WriteFile upstream.
fn copyFile(src: [*:0]const u8, dest: [*:0]const u8) Error!void {
    const data = try readFileAlloc(std.heap.page_allocator, src);
    defer std.heap.page_allocator.free(data);
    try writeFile(dest, data, try fileMode(src));
}

/// Port of fileConfigurator with the paths made parameters so tests can work
/// on a temp directory instead of the host /etc/resolv.conf.
pub const FileConfigurator = struct {
    alloc: std.mem.Allocator,
    config_path: [:0]const u8,
    backup_path: [:0]const u8,
    /// Caller supplies state-manager storage paths, never implicit host paths.
    state_path: ?[:0]const u8 = null,
    recovery_path: ?[:0]const u8 = null,
    original_nameservers: []const []const u8 = &.{},
    original_perms: u32 = 0,
    wg_iface: []const u8 = "",

    pub fn deinit(f: *FileConfigurator) void {
        for (f.original_nameservers) |ns| f.alloc.free(ns);
        f.alloc.free(f.original_nameservers);
        f.original_nameservers = &.{};
    }

    pub fn backupExists(f: *const FileConfigurator) bool {
        return fileExists(f.backup_path.ptr);
    }

    /// Port of fileConfigurator.backup.
    pub fn backup(f: *FileConfigurator) Error!void {
        f.original_perms = try fileMode(f.config_path.ptr);
        try copyFile(f.config_path.ptr, f.backup_path.ptr);
    }

    /// Port of fileConfigurator.restore: copy the backup over the config and
    /// remove the backup.
    pub fn restore(f: *FileConfigurator) Error!void {
        try copyFile(f.backup_path.ptr, f.config_path.ptr);
        if (failed(linux.unlink(f.backup_path.ptr))) return Error.UnlinkFailed;
        f.deinit();
        if (f.state_path) |path| try editState(f.alloc, path, null);
    }

    /// Port of applyDNSConfig/updateConfig: the caller must have backed the
    /// config up first (Go checks isBackupFileExist before calling backup);
    /// the original file is parsed from the backup, search domains merged and
    /// the managed content written. A write error restores the original.
    /// `nb_search_domains` are the NetBird domains (HostDNSConfig already
    /// filtered); `server_ip` is the single nameserver written.
    pub fn apply(
        f: *FileConfigurator,
        nb_search_domains: []const []const u8,
        server_ip: []const u8,
    ) Error!void {
        var arena = std.heap.ArenaAllocator.init(f.alloc);
        defer arena.deinit();
        const a = arena.allocator();
        const raw = try readFileAlloc(a, f.backup_path.ptr);
        const orig = parse(a, raw) catch |err| switch (err) {
            error.OutOfMemory => return err,
            else => ResolvConf{},
        };
        const saved = try f.alloc.alloc([]const u8, orig.name_servers.len);
        var count: usize = 0;
        errdefer {
            for (saved[0..count]) |ns| f.alloc.free(ns);
            f.alloc.free(saved);
        }
        for (orig.name_servers, 0..) |ns, i| {
            saved[i] = try f.alloc.dupe(u8, ns);
            count += 1;
        }
        const merged = try mergeSearchDomains(a, nb_search_domains, orig.search_domains);
        const content = try prepareContent(a, f.backup_path, merged, &.{server_ip}, orig.others);
        writeFile(f.config_path.ptr, content, f.original_perms) catch |err| {
            f.restore() catch {}; // Go logs the restore failure and returns the write error
            return err;
        };
        f.deinit();
        f.original_nameservers = saved;
        // Upstream logs indicator failures without failing a successful apply.
        f.recordShutdown(server_ip) catch {};
    }

    /// Port of createUncleanShutdownIndicator. The persisted address is the
    /// file-manager ShutdownState DNSAddress; the recovery copy is separate
    /// from the ordinary backup, as upstream's state-directory resolv.conf.
    fn recordShutdown(f: *FileConfigurator, address: []const u8) Error!void {
        const state = f.state_path orelse return;
        const recovery = f.recovery_path orelse return Error.OpenFailed;
        try copyFile(f.backup_path.ptr, recovery.ptr);
        var arena = std.heap.ArenaAllocator.init(f.alloc);
        defer arena.deinit();
        const a = arena.allocator();
        const ip = try normalizedAddress(address);
        var ipbuf: [80]u8 = undefined;
        var writer = std.Io.Writer.fixed(&ipbuf);
        switch (ip) {
            .ip4 => |v| writer.print("{d}.{d}.{d}.{d}", .{ v.bytes[0], v.bytes[1], v.bytes[2], v.bytes[3] }) catch return Error.InvalidState,
            .ip6 => |v| {
                const u: std.Io.net.Ip6Address.Unresolved = .{ .bytes = v.bytes, .interface_name = null };
                u.format(&writer) catch return Error.InvalidState;
            },
        }
        const record = std.json.Stringify.valueAlloc(a, .{ .ManagerType = @as(u8, 1), .DNSAddress = writer.buffered(), .WgIface = f.wg_iface }, .{}) catch return Error.OutOfMemory;
        try editState(a, state, record);
    }

    pub fn restoreUncleanShutdownDNS(f: *FileConfigurator) Error!void {
        const state = f.state_path orelse return;
        if (!fileExists(state.ptr)) return;
        const recovery = f.recovery_path orelse return Error.OpenFailed;
        var arena = std.heap.ArenaAllocator.init(f.alloc);
        defer arena.deinit();
        const a = arena.allocator();
        const raw = try readFileAlloc(a, state.ptr);
        if (raw.len == 0) return;
        const members = try readMembers(a, raw);
        var record: ?[]const u8 = null;
        for (members) |m| if (std.mem.eql(u8, m.key, "dns_state")) {
            record = m.value;
        };
        const bytes = record orelse return;
        const parsed = std.json.parseFromSlice(struct { ManagerType: u8, DNSAddress: []const u8, WgIface: []const u8 }, a, bytes, .{ .ignore_unknown_fields = true }) catch return Error.InvalidState;
        if (parsed.value.ManagerType != 1) return;
        const address = try normalizedAddress(parsed.value.DNSAddress);
        const current = try parse(a, try readFileAlloc(a, f.config_path.ptr));
        if (current.name_servers.len == 0 or address.eql(&(try normalizedAddress(current.name_servers[0])))) {
            try copyFile(recovery.ptr, f.config_path.ptr);
        }
        try editState(a, state, null);
    }

    /// Port of restoreHostDNS (without the repair watcher, M14+).
    pub fn restoreHostDNS(f: *FileConfigurator) Error!void {
        return f.restore();
    }
};

// Port of netbird client/internal/dns/file_repair_unix.go (v0.80.0), BSD-3-Clause
/// Upstream has no debounce timer: remove watch during repair, then re-add.
/// This thread owns all repair allocations. The caller stops it before using
/// the configurator to apply or restore, matching upstream lifecycle ordering.
pub const Repair = struct {
    alloc: std.mem.Allocator,
    config: [:0]u8,
    backup: [:0]u8,
    directory: [:0]u8,
    operation: [:0]u8,
    server: []u8,
    domains: [][]const u8,
    state: ?[:0]u8,
    recovery: ?[:0]u8,
    mode: u32,
    fd: linux.fd_t,
    wd: linux.fd_t,
    thread: ?std.Thread = null,
    stopping: std.atomic.Value(bool) = .init(false),
    const mask = linux.IN.MODIFY | linux.IN.CREATE | linux.IN.DELETE | linux.IN.MOVE;
    // Only a stop responsiveness timeout, not a repair debounce.
    const stop_poll_ms = 50;

    pub fn start(a: std.mem.Allocator, fc: *FileConfigurator, domains: []const []const u8, server: []const u8) !*Repair {
        const r = try a.create(Repair);
        errdefer a.destroy(r);
        const config = try a.dupeSentinel(u8, fc.config_path, 0);
        errdefer a.free(config);
        const backup = try a.dupeSentinel(u8, fc.backup_path, 0);
        errdefer a.free(backup);
        const operation = try resolvedPath(a, config);
        errdefer a.free(operation);
        const directory = try a.dupeSentinel(u8, std.fs.path.dirname(operation) orelse ".", 0);
        errdefer a.free(directory);
        const address = try a.dupe(u8, server);
        errdefer a.free(address);
        const copied = try a.alloc([]const u8, domains.len);
        var count: usize = 0;
        errdefer {
            for (copied[0..count]) |d| a.free(d);
            a.free(copied);
        }
        for (domains, 0..) |d, i| {
            copied[i] = try a.dupe(u8, d);
            count += 1;
        }
        const state = if (fc.state_path) |p| try a.dupeSentinel(u8, p, 0) else null;
        errdefer if (state) |p| a.free(p);
        const recovery = if (fc.recovery_path) |p| try a.dupeSentinel(u8, p, 0) else null;
        errdefer if (recovery) |p| a.free(p);
        const fd = linux.inotify_init1(linux.IN.CLOEXEC | linux.IN.NONBLOCK);
        if (failed(fd)) return Error.OpenFailed;
        errdefer _ = linux.close(@intCast(fd));
        const wd = linux.inotify_add_watch(@intCast(fd), directory.ptr, mask);
        if (failed(wd)) return Error.OpenFailed;
        r.* = .{ .alloc = a, .config = config, .backup = backup, .directory = directory, .operation = operation, .server = address, .domains = copied, .state = state, .recovery = recovery, .mode = fc.original_perms, .fd = @intCast(fd), .wd = @intCast(wd) };
        r.thread = try std.Thread.spawn(.{}, run, .{r});
        return r;
    }

    /// Consumes and destroys this pointer. Stop once, before apply or restore.
    pub fn stop(r: *Repair) void {
        r.stopping.store(true, .release);
        if (r.thread) |t| t.join();
        _ = linux.close(r.fd);
        const a = r.alloc;
        a.free(r.operation);
        a.free(r.config);
        a.free(r.backup);
        a.free(r.directory);
        a.free(r.server);
        for (r.domains) |d| a.free(d);
        a.free(r.domains);
        if (r.state) |p| a.free(p);
        if (r.recovery) |p| a.free(p);
        a.destroy(r);
    }

    fn run(r: *Repair) void {
        var events: [4096]u8 align(4) = undefined;
        while (!r.stopping.load(.acquire)) {
            var pfd = [_]linux.pollfd{.{ .fd = r.fd, .events = linux.POLL.IN, .revents = 0 }};
            const rc = linux.poll(&pfd, pfd.len, stop_poll_ms);
            if (failed(rc) or rc == 0) continue;
            const n = linux.read(r.fd, &events, events.len);
            if (failed(n)) continue;
            var offset: usize = 0;
            var relevant = false;
            while (offset + 16 <= n) {
                const bits = std.mem.readInt(u32, events[offset + 4 ..][0..4], .little);
                const len = std.mem.readInt(u32, events[offset + 12 ..][0..4], .little);
                if (offset + 16 + len > n) break;
                const name = std.mem.sliceTo(events[offset + 16 .. offset + 16 + len], 0);
                if (bits & mask != 0 and std.mem.eql(u8, name, std.fs.path.basename(r.operation))) relevant = true;
                offset += 16 + len;
            }
            if (relevant) r.repair() catch {};
        }
    }

    fn repair(r: *Repair) !void {
        var arena = std.heap.ArenaAllocator.init(r.alloc);
        defer arena.deinit();
        const a = arena.allocator();
        const current = try parse(a, try readFileAlloc(a, r.config.ptr));
        var missing = current.name_servers.len == 0 or !std.mem.eql(u8, current.name_servers[0], r.server);
        for (r.domains) |domain| {
            var found = false;
            for (current.search_domains) |d| if (std.mem.eql(u8, domain, d)) {
                found = true;
                break;
            };
            if (!found) missing = true;
        }
        if (!missing) return;
        _ = linux.inotify_rm_watch(r.fd, r.wd);
        defer {
            const wd = linux.inotify_add_watch(r.fd, r.directory.ptr, mask);
            if (!failed(wd)) r.wd = @intCast(wd) else r.stopping.store(true, .release);
        }
        const merged = try mergeSearchDomains(a, r.domains, current.search_domains);
        const content = try prepareContent(a, r.backup, merged, &.{r.server}, current.others);
        writeFile(r.config.ptr, content, r.mode) catch |err| {
            var rollback = FileConfigurator{ .alloc = a, .config_path = r.config, .backup_path = r.backup, .state_path = r.state };
            rollback.restore() catch {};
            return err;
        };
        var fc = FileConfigurator{ .alloc = a, .config_path = r.config, .backup_path = r.backup, .state_path = r.state, .recovery_path = r.recovery };
        fc.recordShutdown(r.server) catch {};
    }
};

fn normalizedAddress(text: []const u8) Error!std.Io.net.IpAddress {
    const ip = std.Io.net.IpAddress.parse(text, 0) catch return Error.InvalidState;
    if (ip == .ip6) {
        const b = ip.ip6.bytes;
        if (std.mem.eql(u8, b[0..12], &.{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255 })) return .{ .ip4 = .{ .bytes = b[12..16].*, .port = 0 } };
    }
    return ip;
}

fn resolvedPath(a: std.mem.Allocator, path: [:0]const u8) Error![:0]u8 {
    const raw = linux.open(path.ptr, .{ .PATH = true, .CLOEXEC = true }, 0);
    if (failed(raw)) return Error.OpenFailed;
    defer _ = linux.close(@intCast(raw));
    var linkbuf: [64]u8 = undefined;
    const link = std.fmt.bufPrintSentinel(&linkbuf, "/proc/self/fd/{d}", .{raw}, 0) catch unreachable;
    var buf: [4096]u8 = undefined;
    const n = linux.readlink(link.ptr, &buf, buf.len);
    if (failed(n) or n == buf.len) return Error.OpenFailed;
    return a.dupeSentinel(u8, buf[0..n], 0);
}

const StateMember = struct { key: []const u8, raw_key: []const u8, value: []const u8 };

/// Preserve raw JSON value bytes rather than round-tripping numbers or nested objects.
fn readMembers(a: std.mem.Allocator, raw: []const u8) Error![]StateMember {
    var scanner = std.json.Scanner.initCompleteInput(a, raw);
    defer scanner.deinit();
    if ((scanner.next() catch return Error.InvalidState) != .object_begin) return Error.InvalidState;
    var members: std.ArrayList(StateMember) = .empty;
    while (true) {
        var key_start = scanner.cursor;
        while (key_start < raw.len and (std.ascii.isWhitespace(raw[key_start]) or raw[key_start] == ',')) : (key_start += 1) {}
        const token = scanner.nextAlloc(a, .alloc_always) catch |err| return if (err == error.OutOfMemory) Error.OutOfMemory else Error.InvalidState;
        if (token == .object_end) break;
        const key = switch (token) {
            .allocated_string => |k| k,
            .string => |k| k,
            else => return Error.InvalidState,
        };
        const key_end = scanner.cursor;
        var value_start = key_end;
        while (value_start < raw.len and (std.ascii.isWhitespace(raw[value_start]) or raw[value_start] == ':')) : (value_start += 1) {}
        scanner.skipValue() catch |err| return if (err == error.OutOfMemory) Error.OutOfMemory else Error.InvalidState;
        var value_end = scanner.cursor;
        while (value_end > value_start and std.ascii.isWhitespace(raw[value_end - 1])) : (value_end -= 1) {}
        try members.append(a, .{ .key = key, .raw_key = raw[key_start..key_end], .value = raw[value_start..value_end] });
    }
    if ((scanner.next() catch return Error.InvalidState) != .end_of_document) return Error.InvalidState;
    return members.items;
}

var state_sequence = std.atomic.Value(u64).init(0);
fn atomicState(path: [:0]const u8, bytes: []const u8) Error!void {
    var buf: [4096]u8 = undefined;
    const tmp = std.fmt.bufPrintSentinel(&buf, "{s}.tmp-{d}-{d}", .{ path, linux.getpid(), state_sequence.fetchAdd(1, .monotonic) }, 0) catch return Error.WriteFailed;
    const raw = linux.open(tmp.ptr, .{ .ACCMODE = .WRONLY, .CREAT = true, .EXCL = true, .CLOEXEC = true }, 0o600);
    if (failed(raw)) return Error.WriteFailed;
    const fd: linux.fd_t = @intCast(raw);
    var closed = false;
    defer {
        if (!closed) _ = linux.close(fd);
        _ = linux.unlink(tmp.ptr);
    }
    var sent: usize = 0;
    while (sent < bytes.len) {
        const n = linux.write(fd, bytes[sent..].ptr, bytes.len - sent);
        if (failed(n) or n == 0) return Error.WriteFailed;
        sent += n;
    }
    const rc = linux.close(fd);
    closed = true;
    if (failed(rc) or failed(linux.rename(tmp.ptr, path.ptr))) return Error.WriteFailed;
}

fn editState(alloc: std.mem.Allocator, path: [:0]const u8, record: ?[]const u8) Error!void {
    var arena = std.heap.ArenaAllocator.init(alloc);
    defer arena.deinit();
    const a = arena.allocator();
    const raw = if (fileExists(path.ptr)) try readFileAlloc(a, path.ptr) else "";
    const members = if (raw.len > 0) try readMembers(a, raw) else &.{};
    var out: std.ArrayList(u8) = .empty;
    try out.append(a, '{');
    var count: usize = 0;
    for (members) |m| {
        if (std.mem.eql(u8, m.key, "dns_state")) continue;
        if (count > 0) try out.append(a, ',');
        try out.appendSlice(a, m.raw_key);
        try out.append(a, ':');
        try out.appendSlice(a, m.value);
        count += 1;
    }
    if (record) |r| {
        if (count > 0) try out.append(a, ',');
        try out.appendSlice(a, "\"dns_state\":");
        try out.appendSlice(a, r);
        count += 1;
    }
    try out.append(a, '}');
    if (count == 0) {
        if (fileExists(path.ptr) and failed(linux.unlink(path.ptr))) return Error.UnlinkFailed;
    } else try atomicState(path, out.items);
}
