// Tests for the resolv.conf file backend: parser, content builder, search
// domain merge limits, and the backup/apply/restore cycle on a temp path
// (never the host /etc/resolv.conf).

const std = @import("std");
const linux = std.os.linux;
const file = @import("file.zig");
const builtin = @import("builtin");

const testing = std.testing;

fn failed(rc: usize) bool {
    return rc > 0xfffffffffffff000;
}

var tmp_dir_path: [64]u8 = undefined;
var config_path_buf: [80]u8 = undefined;
var backup_path_buf: [96]u8 = undefined;
var temp_counter = std.atomic.Value(u32).init(0);

fn tempPaths() struct { dir: [:0]const u8, config: [:0]const u8, backup: [:0]const u8 } {
    const n = temp_counter.fetchAdd(1, .monotonic);
    const dir = std.fmt.bufPrintSentinel(&tmp_dir_path, "/tmp/dnsfile-{x}-{d}", .{ linux.getpid(), n }, 0) catch unreachable;
    const rc = linux.mkdir(dir.ptr, 0o755);
    if (failed(rc)) return .{ .dir = dir, .config = "", .backup = "" };
    const config = std.fmt.bufPrintSentinel(&config_path_buf, "{s}/resolv.conf", .{dir}, 0) catch unreachable;
    const backup = std.fmt.bufPrintSentinel(&backup_path_buf, "{s}/resolv.conf.original.netbird", .{dir}, 0) catch unreachable;
    return .{ .dir = dir, .config = config, .backup = backup };
}

test "parse resolv.conf contents" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const contents =
        "# a comment\n" ++
        "search corp.example. other.example.\n" ++
        "domain dropped.example.\n" ++
        "options rotate timeout:1\n" ++
        "nameserver 10.0.0.1\n" ++
        "nameserver 2001:db8::1\n" ++
        "nameserver not-an-ip\n" ++
        "nameserver\n" ++
        "\n" ++
        "   indented.example.org   \n";
    const rc = try file.parse(a, contents);

    try testing.expectEqual(@as(usize, 2), rc.name_servers.len);
    try testing.expectEqualStrings("10.0.0.1", rc.name_servers[0]);
    try testing.expectEqualStrings("2001:db8::1", rc.name_servers[1]);
    try testing.expectEqual(@as(usize, 2), rc.search_domains.len);
    try testing.expectEqualStrings("corp.example.", rc.search_domains[0]);
    // a second search line replaces the first list; the indented line and the
    // stripped rotate option land in others
    try testing.expectEqual(@as(usize, 2), rc.others.len);
    try testing.expectEqualStrings("options timeout:1", rc.others[0]);
    try testing.expectEqualStrings("indented.example.org", rc.others[1]);

    const rc2 = try file.parse(a, "search first.example.\nsearch second.example.\n");
    try testing.expectEqual(@as(usize, 1), rc2.search_domains.len);
    try testing.expectEqualStrings("second.example.", rc2.search_domains[0]);

    // rotate-only options line is dropped, "domain" skipped, empty errors
    const rc3 = try file.parse(a, "options rotate\n");
    try testing.expectEqual(@as(usize, 0), rc3.others.len);
    try testing.expectError(file.Error.EmptyFile, file.parse(a, ""));
}

test "prepareContent layout" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const out = try file.prepareContent(
        a,
        "/etc/resolv.conf.original.netbird",
        &.{ "corp.example.", "other.example." },
        &.{"100.100.111.1"},
        &.{"options timeout:1"},
    );
    const want =
        "# Generated by NetBird\n" ++
        "# The original file can be restored from /etc/resolv.conf.original.netbird\n" ++
        "\n" ++
        "options timeout:1\n" ++
        "search corp.example. other.example.\n" ++
        "nameserver 100.100.111.1\n";
    try testing.expectEqualStrings(want, out);
}

test "mergeSearchDomains dedupe and caps" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    // dedupe keeps first occurrence; NetBird domains come first
    const merged = try file.mergeSearchDomains(
        a,
        &.{ "nb.example.", "dup.example." },
        &.{ "orig.example.", "dup.example." },
    );
    try testing.expectEqual(@as(usize, 3), merged.len);
    try testing.expectEqualStrings("nb.example.", merged[0]);
    try testing.expectEqualStrings("dup.example.", merged[1]);
    try testing.expectEqualStrings("orig.example.", merged[2]);

    // no more than 6 domains
    var many: [8][]const u8 = undefined;
    for (&many, 0..) |*m, i| m.* = try std.fmt.allocPrint(a, "d{d}.example.", .{i});
    const capped = try file.mergeSearchDomains(a, &many, &.{});
    try testing.expectEqual(@as(usize, file.max_search_domains), capped.len);

    // a domain longer than the 256-character line limit is skipped, the next
    // short one is still appended
    const long_domain = try a.alloc(u8, 259);
    @memset(long_domain[0..250], 'x');
    @memcpy(long_domain[250..], ".example.");
    const skipped = try file.mergeSearchDomains(a, &.{ long_domain, "short.example." }, &.{});
    try testing.expectEqual(@as(usize, 1), skipped.len);
    try testing.expectEqualStrings("short.example.", skipped[0]);
}

test "backup apply restore cycle on temp paths" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const tp = tempPaths();
    if (tp.config.len == 0) return error.SkipZigTest;
    defer _ = linux.rmdir(tp.dir.ptr);

    const original = "# original\nnameserver 8.8.8.8\nsearch home.example.\n";
    {
        const fd_usize = linux.open(tp.config.ptr, .{ .ACCMODE = .WRONLY, .CREAT = true, .TRUNC = true }, 0o600);
        try testing.expect(!failed(fd_usize));
        const fd: linux.fd_t = @intCast(fd_usize);
        _ = linux.write(fd, original.ptr, original.len);
        _ = linux.close(fd);
    }

    var fc = file.FileConfigurator{
        .alloc = a,
        .config_path = tp.config,
        .backup_path = tp.backup,
    };

    // apply requires the backup (Go checks isBackupFileExist first)
    try testing.expect(!fc.backupExists());
    try fc.backup();
    try testing.expect(fc.backupExists());

    const nb_domains = [_][]const u8{ "nb.example.", "net.example." };
    try fc.apply(&nb_domains, "100.100.111.1");

    // managed content on the config path, original untouched in the backup
    const managed = try file.parse(a, try file.readFileAlloc(a, tp.config.ptr));
    try testing.expectEqual(@as(usize, 1), managed.name_servers.len);
    try testing.expectEqualStrings("100.100.111.1", managed.name_servers[0]);
    try testing.expectEqual(@as(usize, 3), managed.search_domains.len);
    try testing.expectEqualStrings("nb.example.", managed.search_domains[0]);
    try testing.expectEqualStrings("net.example.", managed.search_domains[1]);
    try testing.expectEqualStrings("home.example.", managed.search_domains[2]);

    // a second apply keeps the FIRST backup (original content again available)
    try fc.apply(&.{"again.example."}, "100.100.111.2");
    const managed2 = try file.parse(a, try file.readFileAlloc(a, tp.config.ptr));
    try testing.expectEqualStrings("100.100.111.2", managed2.name_servers[0]);
    // search list rebuilt from the NetBird domains + the backup's own
    try testing.expectEqual(@as(usize, 2), managed2.search_domains.len);
    try testing.expectEqualStrings("again.example.", managed2.search_domains[0]);
    try testing.expectEqualStrings("home.example.", managed2.search_domains[1]);

    try fc.restoreHostDNS();
    try testing.expect(!fc.backupExists());
    const restored = try file.parse(a, try file.readFileAlloc(a, tp.config.ptr));
    try testing.expectEqual(@as(usize, 1), restored.name_servers.len);
    try testing.expectEqualStrings("8.8.8.8", restored.name_servers[0]);
    try testing.expectEqual(@as(usize, 1), restored.search_domains.len);
    try testing.expectEqualStrings("home.example.", restored.search_domains[0]);
}

test "original modes survive recreation on apply and restore" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    for ([_]u32{ 0o600, 0o640 }) |mode| {
        const tp = tempPaths();
        defer _ = linux.rmdir(tp.dir.ptr);
        defer _ = linux.unlink(tp.config.ptr);
        defer _ = linux.unlink(tp.backup.ptr);
        const fd = linux.open(tp.config.ptr, .{ .ACCMODE = .WRONLY, .CREAT = true }, mode);
        try testing.expect(!failed(fd));
        try testing.expectEqual(@as(usize, 0), linux.fchmod(@intCast(fd), mode));
        const original = "nameserver 8.8.8.8\n";
        _ = linux.write(@intCast(fd), original.ptr, original.len);
        _ = linux.close(@intCast(fd));
        var fc = file.FileConfigurator{ .alloc = arena.allocator(), .config_path = tp.config, .backup_path = tp.backup };
        try fc.backup();
        _ = linux.unlink(tp.config.ptr);
        try fc.apply(&.{}, "100.100.111.1");
        var stat: [144]u8 align(8) = undefined;
        try testing.expectEqual(@as(usize, 0), linux.syscall4(.newfstatat, @bitCast(@as(isize, linux.AT.FDCWD)), @intFromPtr(tp.config.ptr), @intFromPtr(&stat), 0));
        try testing.expectEqual(mode, std.mem.readInt(u32, stat[if (builtin.cpu.arch == .aarch64) 16 else 24 ..][0..4], .little) & 0o777);
        _ = linux.unlink(tp.config.ptr);
        try fc.restore();
        try testing.expectEqual(@as(usize, 0), linux.syscall4(.newfstatat, @bitCast(@as(isize, linux.AT.FDCWD)), @intFromPtr(tp.config.ptr), @intFromPtr(&stat), 0));
        try testing.expectEqual(mode, std.mem.readInt(u32, stat[if (builtin.cpu.arch == .aarch64) 16 else 24 ..][0..4], .little) & 0o777);
    }
}

test "shutdown state conditional recovery and clean removal" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    for ([_]bool{ false, true }) |changed| {
        const tp = tempPaths();
        const state = try std.fmt.allocPrintSentinel(a, "{s}/dns_state", .{tp.dir}, 0);
        const recovery = try std.fmt.allocPrintSentinel(a, "{s}/recovery", .{tp.dir}, 0);
        defer _ = linux.rmdir(tp.dir.ptr);
        defer _ = linux.unlink(tp.config.ptr);
        defer _ = linux.unlink(tp.backup.ptr);
        defer _ = linux.unlink(state.ptr);
        defer _ = linux.unlink(recovery.ptr);
        const original = "nameserver 8.8.8.8\n";
        try testWrite(tp.config.ptr, original);
        var fc = file.FileConfigurator{ .alloc = a, .config_path = tp.config, .backup_path = tp.backup, .state_path = state, .recovery_path = recovery };
        try fc.backup();
        try fc.apply(&.{}, "100.100.111.1");
        try testing.expect(file.fileExists(state.ptr));
        const external = "nameserver 9.9.9.9\n";
        if (changed) try testWrite(tp.config.ptr, external);
        // Survives a process/configurator restart and loss of the ordinary backup.
        _ = linux.unlink(tp.backup.ptr);
        var restarted = file.FileConfigurator{ .alloc = a, .config_path = tp.config, .backup_path = tp.backup, .state_path = state, .recovery_path = recovery };
        try restarted.restoreUncleanShutdownDNS();
        try testing.expectEqualStrings(if (changed) external else original, try file.readFileAlloc(a, tp.config.ptr));
        try fc.backup();
        try fc.apply(&.{}, "100.100.111.1");
        try fc.restoreHostDNS();
        try testing.expect(!file.fileExists(state.ptr));
    }
}

fn testWrite(path: [*:0]const u8, contents: []const u8) !void {
    const fd = linux.open(path, .{ .ACCMODE = .WRONLY, .CREAT = true, .TRUNC = true }, 0o600);
    try testing.expect(!failed(fd));
    defer _ = linux.close(@intCast(fd));
    try testing.expectEqual(contents.len, linux.write(@intCast(fd), contents.ptr, contents.len));
}
